name: Upload file to firebase
description: "Upload file to firebase"
branding:
  icon: "git-pull-request"
  color: purple
inputs:
  service-json:
    description: "Service json for Google Cloud"
    required: true
  github-token:
    description: "Token for GitHub access"
    required: true
  bucketName:
    description: "Bucket name"
    required: true
  bucketFolder:
    description: "Folder for uploading the file"
    required: true
  filePath:
    description: "Path to a file to be uploaded"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
